name: Onwards Up
favicon: null
layout_spectrum: 0.6043841254431754
typography_spectrum: 0.5351598868146539
title: Onwards Up - digital product consultants
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-53571222-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.23016160167753696
  lightness: 0.16149114863947034
  saturation: 0.9508209901396185
  rhythmicContrast: 0.5760526966769248
purpose: []
