name: Onwards Up
favicon: null
layout_spectrum: 0.78795
typography_spectrum: 0.23178
title: Onwards Up
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-53571222-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#595959'
    - '#ffffff'
    - '#121212'
    - '#929292'
    - '#2683f9'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
